vim.api.nvim_create_autocmd({ "VimEnter" }, {
	callback = function()
		local map = vim.keymap.set

		map("n", "<BS>", "<C-b>")
		map("n", "<Delete>", "<C-f>")
		map('n', '<C-S-e>', '5<C-e>')
		map('n', '<C-S-y>', '5<C-y>')
		map('n', 'x', '<Nop>')
		map('n', 'X', 'd^')
		map('n', 'S', 'c^')
		map("n", "xd", "<cmd>bd<CR>")
		map("n", "xb", "<cmd>b#<CR>")
		map("n", "xe", "<cmd>Explore<CR>")
		map('n', '<Space><Space>', 'gg=G<C-o>')
		map('n', 'gd', function() vim.lsp.buf.definition() end)
		map('n', 'gn', function() vim.lsp.buf.rename() end)
		map('n', 'gr', function() vim.lsp.buf.references() end)
		map('n', '[e', function() vim.diagnostic.goto_prev() end)
		map('n', ']e', function() vim.diagnostic.goto_next() end)
		map("n", "Q", "q")
		map("n", "q", "ZZ")
		map("n", "K", "25k")
		map("n", "J", "25j")
		map('n', '^s', function() vim.o.spell = not vim.o.spell end)
		map('n', '^r', function() vim.o.relativenumber = not vim.o.relativenumber end)
		map('n', 'zh', '<C-w>h')
		map('n', 'zj', '<C-w>j')
		map('n', 'zk', '<C-w>k')
		map('n', 'zl', '<C-w>l')
		map('n', 'zw', '<C-w>w')
		map('n', 'zo', '<C-o>')
		map('n', 'zi', '<C-i>')
		map("n", "zs", "m'")
		map('n', '<Space>', '<Nop>')
		map('n', '<CR>', '<Nop>')
		map('n', 'n', 'nzzzv')
		map('n', 'N', 'Nzzzv')
		map('n', 'M', ':w|make|cw<CR>')
		map('n', ']q', ':cn<CR>')
		map('n', '[q', ':cp<CR>')
		map({ 'o', 'v' }, 'K', '5k')
		map({ 'o', 'v' }, 'J', '5j')
		map({ "n", "v", "o" }, "L", "5l")
		map({ "n", "v", "o" }, "H", "5h")
		map({ "n", "v", "o" }, "gl", "$l")
		map({ "n", "v", "o" }, "gh", "^")

		map('i', '<Esc>', '<Right><Esc>')
		map('i', '<C-e>', '<C-x><C-e>')
		map('i', '<C-y>', '<C-x><C-y>')
		map('i', '<C-f>', '<C-x><C-f>')
		map('i', 'e', function() if vim.fn.pumvisible() ~= 0 then return "<C-e>" else return "e" end end, { expr = true, noremap = true })
		map('i', 'y', function() if vim.fn.pumvisible() ~= 0 then return "<C-y>" else return "y" end end, { expr = true, noremap = true })
		map('i', 'n', function() if vim.fn.pumvisible() ~= 0 then return "<C-n>" else return "n" end end, { expr = true, noremap = true })
		map('i', 'p', function() if vim.fn.pumvisible() ~= 0 then return "<C-p>" else return "p" end end, { expr = true, noremap = true })

		map('v', '<C-k>', ":m '<-2<CR>gv=gv")
		map('v', '<C-j>', ":m '>+1<CR>gv=gv")
		map('v', 'v', "<C-v>")
		map('v', 'aa', 'VggoG')

		map('o', '2', 'i"')
		map('o', '7', "i'")
		map('o', '9', 'i(')
		map('o', ']', 'i]')
		map('o', '}', 'i}')
		map('o', '.', 'i>')

	end })
